'use strict';

const path = require('path');
const { AppError } = require('../middleware/errorHandler');
const logger = require('../utils/logger');
const { getLanguageFromPath } = require('../utils/pathHelpers');

// ─────────────────────────────────────────────────────────────────────────────
// Validation Constants
// ─────────────────────────────────────────────────────────────────────────────

/** Characters not allowed in file paths generated by AI */
const INVALID_PATH_CHARS = /[<>:"|?*\x00-\x1F]/;

/** Minimum number of files that constitute a valid project */
const MIN_FILES_REQUIRED = 3;

/** Maximum file content length (4 MB) — prevent runaway generation */
const MAX_FILE_CONTENT_LENGTH = 4 * 1024 * 1024;

/** Placeholder patterns that indicate incomplete AI generation */
const PLACEHOLDER_PATTERNS = [
  /\/\/\s*TODO(?:\s*:|\s)/i,
  /\/\/\s*PLACEHOLDER/i,
  /\/\/\s*IMPLEMENT\s+THIS/i,
  /throw new Error\(['"]Not implemented/i,
  /\/\/\s*Your code here/i,
  /console\.log\(['"]Not implemented/i,
  /return null;\s*\/\/\s*TODO/i,
];

/** Valid language identifiers accepted in the output contract */
const VALID_LANGUAGES = new Set([
  'javascript', 'jsx', 'typescript', 'tsx',
  'json', 'html', 'css', 'markdown',
  'yaml', 'plaintext', 'bash', 'shell', 'sql',
]);

/**
 * ResponseParserService — Stages 9–10 of the AI Generation Pipeline.
 *
 * Acts as a strict quality gate between AI output and the filesystem.
 * Only valid, complete, safe responses are allowed through.
 *
 * Stage 9 — Validation:   Structural, file-level, path, and content checks.
 * Stage 10 — Review Pass: Normalization, language inference, warning detection.
 *
 * Any validation failure throws an AppError(502) which triggers a retry
 * in the generation pipeline.
 */
class ResponseParserService {

  // ── Public API ─────────────────────────────────────────────────────────────

  /**
   * Validates and normalizes the raw AI response object.
   * @param {object} rawResponse - Parsed JSON from GeminiProvider.
   * @param {boolean} [isUpdate=false] - If this validation is for an incremental update.
   * @returns {ValidatedProjectResponse} Normalized, safe project specification.
   * @throws {AppError} If the response fails any validation rule.
   */
  validate(rawResponse, isUpdate = false) {
    logger.info('[ResponseParserService] Stage 9: Starting response validation...');

    // ── Stage 9 — Validation ──────────────────────────────────────────────
    this._validateType(rawResponse);
    this._validateRequiredKeys(rawResponse, isUpdate);
    this._validateProjectName(rawResponse.projectName);
    this._validateDependencies(rawResponse.dependencies);
    this._validateFiles(rawResponse.files);
    this._validateNoDuplicatePaths(rawResponse.files);

    logger.info(`[ResponseParserService] Stage 9 passed. ${rawResponse.files.length} files validated.`);
    logger.info('[ResponseParserService] Stage 10: Starting review pass...');

    // ── Stage 10 — Review Pass ────────────────────────────────────────────
    const reviewed = this._reviewPass(rawResponse);

    logger.info(
      `[ResponseParserService] Stage 10 complete. ` +
      `Files: ${reviewed.files.length}, Warnings: ${reviewed.reviewWarnings.length}`
    );

    return reviewed;
  }

  // ── Stage 9 — Validation Methods ──────────────────────────────────────────

  /**
   * 9-0: Ensure the response is a plain object, not null/array/primitive.
   */
  _validateType(response) {
    if (!response || typeof response !== 'object' || Array.isArray(response)) {
      throw new AppError(
        'AI response is not a valid JSON object. Please try again.',
        502
      );
    }
  }

  /**
   * 9-A: Required top-level keys.
   */
  _validateRequiredKeys(response, isUpdate = false) {
    const required = ['projectName', 'description', 'files'];
    const missing = required.filter((key) => !response[key]);

    if (missing.length > 0) {
      throw new AppError(
        `AI response is missing required fields: ${missing.join(', ')}. ` +
        'The model did not follow the output contract. Please try again.',
        502
      );
    }

    if (!Array.isArray(response.files)) {
      throw new AppError(
        '"files" must be an array. The AI response has an invalid structure.',
        502
      );
    }

    const minAllowed = isUpdate ? 1 : MIN_FILES_REQUIRED;
    if (response.files.length < minAllowed) {
      throw new AppError(
        `AI response contains only ${response.files.length} file(s). ` +
        `A minimum of ${minAllowed} files is required for a valid project. ` +
        'The model generated an incomplete response. Please try again.',
        502
      );
    }
  }

  /**
   * 9-B: Project name must be a valid kebab-case string.
   */
  _validateProjectName(name) {
    if (typeof name !== 'string' || name.trim().length === 0) {
      throw new AppError('AI response has an invalid or empty project name.', 502);
    }
    if (name.length > 100) {
      throw new AppError('Project name is too long (max 100 characters).', 502);
    }
    // Allow letters, numbers, hyphens, underscores, spaces (we'll normalize)
    if (/[<>:"/\\|?*]/.test(name)) {
      throw new AppError(
        `Project name "${name}" contains invalid characters.`,
        502
      );
    }
  }

  /**
   * 9-C: Dependencies must be an object with frontend/backend arrays.
   */
  _validateDependencies(deps) {
    if (!deps || typeof deps !== 'object' || Array.isArray(deps)) {
      // Non-fatal — we'll provide defaults in the review pass
      return;
    }

    for (const env of ['frontend', 'backend']) {
      if (deps[env] !== undefined && !Array.isArray(deps[env])) {
        throw new AppError(
          `dependencies.${env} must be an array. Got: ${typeof deps[env]}`,
          502
        );
      }
    }
  }

  /**
   * 9-D: Per-file structural and content validation.
   */
  _validateFiles(files) {
    for (let i = 0; i < files.length; i++) {
      const file = files[i];

      // Must be a plain object
      if (!file || typeof file !== 'object' || Array.isArray(file)) {
        throw new AppError(`File at index ${i} is not a valid object.`, 502);
      }

      // Must have a non-empty path
      if (!file.path || typeof file.path !== 'string' || file.path.trim() === '') {
        throw new AppError(`File at index ${i} has an invalid or missing "path" field.`, 502);
      }

      // Path must not contain dangerous characters
      if (INVALID_PATH_CHARS.test(file.path)) {
        throw new AppError(
          `File "${file.path}" contains invalid path characters.`,
          502
        );
      }

      // Must not be an absolute path or directory traversal
      const normalizedFilePath = path.normalize(file.path.replace(/\\/g, '/'));
      if (path.isAbsolute(normalizedFilePath) || normalizedFilePath.startsWith('..')) {
        throw new AppError(
          `File "${file.path}" has a dangerous path (absolute or traversal). ` +
          'This is a security violation.',
          502
        );
      }

      // Must have content
      if (!file.content || typeof file.content !== 'string' || file.content.trim().length === 0) {
        throw new AppError(
          `File "${file.path}" has empty or missing content. ` +
          'Every file must have complete, working content.',
          502
        );
      }

      // Content must not exceed max size
      if (file.content.length > MAX_FILE_CONTENT_LENGTH) {
        throw new AppError(
          `File "${file.path}" exceeds the maximum content size of 4MB. ` +
          'Please generate smaller files.',
          502
        );
      }
    }
  }

  /**
   * 9-E: No two files can have the same normalized path.
   */
  _validateNoDuplicatePaths(files) {
    const seen = new Map();
    for (const file of files) {
      const normalized = file.path.replace(/\\/g, '/').toLowerCase().trim();
      if (seen.has(normalized)) {
        throw new AppError(
          `Duplicate file path detected: "${file.path}". ` +
          `Conflicts with previously seen: "${seen.get(normalized)}". ` +
          'The AI generated conflicting files.',
          502
        );
      }
      seen.set(normalized, file.path);
    }
  }

  // ── Stage 10 — Review Pass ─────────────────────────────────────────────────

  /**
   * Normalizes the validated response and collects non-fatal warnings.
   * Does NOT throw — warnings are logged and returned for observability.
   */
  _reviewPass(response) {
    const warnings = [];
    const validFiles = [];

    for (const file of response.files) {
      const content = file.content;

      // Check for placeholder patterns (warn but don't reject)
      const hasPlaceholder = PLACEHOLDER_PATTERNS.some((pattern) => pattern.test(content));
      if (hasPlaceholder) {
        warnings.push(`File "${file.path}" may contain placeholder or incomplete code.`);
        logger.warn(`[ResponseParserService] Placeholder detected: ${file.path}`);
      }

      // Validate/normalize language field
      const inferredLanguage = getLanguageFromPath(file.path);
      const language = (typeof file.language === 'string' && VALID_LANGUAGES.has(file.language))
        ? file.language
        : inferredLanguage;

      // Normalize the file entry
      validFiles.push({
        path: file.path.replace(/\\/g, '/').trim(),
        content: file.content,
        language,
        purpose: typeof file.purpose === 'string' ? file.purpose.trim() : '',
        deleted: !!file.deleted,
      });
    }

    // Run AI Code Review checks
    this._runCodeReviewChecks(validFiles, response.dependencies, warnings);

    if (warnings.length > 0) {
      logger.warn(`[ResponseParserService] ${warnings.length} review warning(s) detected.`);
    }

    // Normalize project name to kebab-case
    const normalizedProjectName = response.projectName
      .trim()
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-_]/g, '');

    return {
      projectName: normalizedProjectName || 'generated-project',
      description: (response.description || '').trim(),
      summary: (response.summary || response.description || '').trim(),
      dependencies: {
        frontend: Array.isArray(response.dependencies?.frontend)
          ? response.dependencies.frontend.filter((d) => typeof d === 'string')
          : [],
        backend: Array.isArray(response.dependencies?.backend)
          ? response.dependencies.backend.filter((d) => typeof d === 'string')
          : [],
      },
      folderTree: Array.isArray(response.folderTree)
        ? response.folderTree.filter((f) => typeof f === 'string').map((f) => f.replace(/\\/g, '/'))
        : [],
      files: validFiles,
      reviewWarnings: warnings,
    };
  }

  _runCodeReviewChecks(files, dependencies, warnings) {
    const allPaths = new Set(files.map(f => f.path.replace(/\\/g, '/').toLowerCase()));

    for (const file of files) {
      if (file.deleted) continue;
      if (!file.path.endsWith('.js') && !file.path.endsWith('.jsx')) continue;

      const content = file.content;
      const importRegex = /import\s+[\s\S]*?\s+from\s+['"]([^'"]+)['"]/g;
      let match;
      const seenImports = new Set();

      while ((match = importRegex.exec(content)) !== null) {
        const importPath = match[1];
        
        // 1. Duplicate imports
        if (seenImports.has(importPath)) {
          warnings.push(`File "${file.path}" contains duplicate import: "${importPath}".`);
        }
        seenImports.add(importPath);

        // 2. Relative path imports
        if (importPath.startsWith('.') || importPath.startsWith('@/')) {
          let resolved = importPath.replace(/^@\//, 'frontend/src/');
          if (importPath.startsWith('.')) {
            const currentDir = file.path.includes('/') ? file.path.substring(0, file.path.lastIndexOf('/')) : '';
            const combined = currentDir ? currentDir + '/' + importPath : importPath;

            const parts = combined.split('/');
            const stack = [];
            for (const part of parts) {
              if (part === '.' || part === '') continue;
              if (part === '..') stack.pop();
              else stack.push(part);
            }
            resolved = stack.join('/');
          }

          const candidates = [
            resolved,
            resolved + '.jsx',
            resolved + '.js',
            resolved + '.json',
            resolved + '/index.jsx',
            resolved + '/index.js'
          ].map(c => c.toLowerCase());

          const resolvedFileExists = candidates.some(c => allPaths.has(c));
          if (!resolvedFileExists && !file.path.startsWith('backend/')) {
            warnings.push(`File "${file.path}" has a potential broken import: "${importPath}" (resolved as: ${resolved})`);
          }
        }
      }
    }
  }
}

module.exports = new ResponseParserService();
